company = input("请输入公司名称：")
name = input("请输入名字：")
job = input("请输入公司职位：")
phone = input("请输入电话号码：")
mailbox = input("请输入邮箱：")
print("*"*50)
print(company)
print()
print("%s(%s)\n" % (name , job))
print("电话：%s" % (phone))
print("邮箱：%s" % (mailbox))
print("*"*50)